name: WeatherVaneBot

# Schedule to run every day at 11am PST (18:00 UTC)
on:
  workflow_dispatch
    
  #schedule: 
   # - cron: '*/10 * * * *'

# Define job
jobs:

  # Define OS
  WeatherVaneBot-post:
    runs-on: windows-latest
    
    # Set Twitter credentials stored in repo secrets as environment variables
    env: 
      WEATHER_VANE_BOT_API_KEY: ${{ secrets.WEATHER_VANE_BOT_API_KEY }}
      WEATHER_VANE_BOT_API_SECRET: ${{ secrets.WEATHER_VANE_BOT_API_SECRET }}
      WEATHER_VANE_BOT_ACCESS_KEY: ${{ secrets.WEATHER_VANE_BOT_ACCESS_KEY }}
      WEATHER_VANE_BOT_ACCESS_SECRET: ${{ secrets.WEATHER_VANE_BOT_ACCESS_SECRET }}
      GITHUB_PAT: ${{ secrets.BOT_TOKEN }}
    # List steps to be taken
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install CRAN packages
        run: Rscript -e "install.packages(c('dplyr', 'tibble', 'stringi', 'httpuv', 'pak'), repos = 'https://cloud.r-project.org/', dependecies = TRUE)"
      - name: Install rtweet package
        run: Rscript -e "pak::pkg_install('ropensci/rtweet')"
      - name: Create and post tweet
        run: Rscript WeatherVane.R

